-  name: ssh | instance IP
   debug:
    msg: "{{ gcp_compute_address.address }}"
  
- name: ssh | Set connection_host to Public IP for initial communication
  set_fact:
    ansible_ssh_host: "{{ gcp_compute_address.address }}"

- name: ssh | Wait for SSH to come up
  wait_for:
    port: 22
    host: '{{ ansible_ssh_host }}'
    search_regex: OpenSSH
    delay: 2
    timeout: 300
  connection: local


