---
# We are setting up a reverse proxy to http://127.0.0.1:8080

nginx_revproxy_sites:                                         
  "{{ ansible_ssh_host }}":                                   # Domain name is not actually working
    domains:                                                  # List of server_name aliases
      - "{{ ansible_ssh_host }}"
      - "{{ inventory_hostname }}"
    upstreams:                                                # List of Upstreams
      - { backend_address: 127.0.0.1, backend_port: 8080 }
    ssl: true                                                 
    hsts_max_age: 63072000                                    
    letsencrypt: false                                        
